### ISSUE TITLE
Connection Problems

### ISSUE THREAD

**Issue by alexz707** [hassio-addons/addon-traccar#16]
# Problem/Motivation
I want to integrate traccar into home assistent.
Traccar server with maria db is up and running. (latest version)
Traccar server receives location updates over a forwarded port and is reachable from the sidemenu.
Home Assistant is running on hass os with duckdns running.

In the traccar config I wrote 8082 as port.

config of component:
```
device_tracker:
 - platform: traccar
  host: a0d7b954-traccar
  port: 8082
  ssl: True
  verify_ssl: False
  username: !secret traccar_user
  password: !secret traccar_pass
```

## Expected behavior

Device appears in home assistant

## Actual behavior

The component doesn't connect to traccar.
In the log it only says:

` 2019-07-08 22:35:21 DEBUG (MainThread [homeassistant.components.traccar.device_tracker] Testing connection to Traccar`

every 30 sec there is a new log entry.
that's all information I get.
I scanned the open ports from my hass.io internal IP and port 8082 is open.
I tried to connect with firefox and it works when it's https (without verification turned on)

I have installed the IDE addon and there I can open a shell.
In the shell I have tried to ping a0d7b954-traccar but it doesn't find it.

```
➜  /workspace ping core-mariadb
PING core-mariadb (172.30.33.0): 56 data bytes
64 bytes from 172.30.33.0: seq=0 ttl=64 time=0.214 ms
--- core-mariadb ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.214/0.283/0.352 ms
➜  /workspace ping a0d7b954-traccar
ping: bad address 'a0d7b954-traccar'
```

I'm not sure what to do now.
So I guess the docker traccar container is maybe not "registered" with it's hostname?
restarting didn't fix the problem...

I hope someone can help me!
Thanks

**Comment by brdr-lauridsen** [comment]
I am having the same problem and was suggested by frenck Try localhost or 127.0.0.1 as the host to connect to in the HA integration. 

Personally, I still haven't had any luck and I checked with portainer, Traccar is the only docker image without an assigned IP or binding Port... If you figure it out please post it here for me too 😃

**Comment by BatterBits** [comment]
Hi  alexz707

I suggest that you get this working without the SSL settings at "true". I have the same setup -Traccar on Hassio, with MariaDB -working perfectly. It uses SSL - the certificate is obtained by the Nginx Proxy Manager, so the default (ssl: false) settings work. In the Hassio config:

`
{
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}
` 

And the default config in configuration.yaml:

`
#Device trackers
device_tracker:
  - platform: traccar
    host: a0d7b954-traccar
    port: 8072
    username: *****
    password: ******
`

Note that I am using the default port of 8072 on my setup - if you change it, you need to change it in both places.

Hope this helps

**Comment by igorbljahhin** [comment]
Same issue here. Hostname "a0d7b954-traccar" is reported as "bad address", if ping it from IDE and Home Assistant keeps saying "Testing connection to Traccar" in log.

What should I do?

**Comment by alexz707** [comment]
Ok, without SSL is not an option because of the duckdns.
I finally got it working by using 127.0.0.1.

My config looks like that:
```
device_tracker:
- platform: traccar
  host: 127.0.0.1
  port: 8082
  ssl: True
  verify_ssl: False
  username: !secret traccar_user
  password: !secret traccar_pass
```

Maybe this should be noted in the documentation?
Thanks for your help!

**Comment by igorbljahhin** [comment]
I tried to put 127.0.0.1, but it does not work (why it should to work, at all! :) ).

My current configuration is 

```
device_tracker:
  - platform: bluetooth_tracker
  - platform: bluetooth_le_tracker
  - platform: traccar
    host: 127.0.0.1
    port: 8092
    ssl: false
    verify_ssl: false
    username: !secret traccar_username
    password: !secret traccar_password
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false
```

The question is, how to make Traccar server address ```a0d7b954-traccar``` available to Home Assistant?

**Comment by BatterBits** [comment]
> 
> 
> I tried to put 127.0.0.1, but it does not work (why it should to work, at all! :) ).
> 
This is because the 127.0.0.1 ip address is a "special" ip address, which means "localhost"

> My current configuration is
> 
> ```
>     host: 127.0.0.1
>     port: 8092
> ```
You have changed the default port, in your configuration.yaml - have you also changed it in the traccar addon config section?

![image](https://user-images.githubusercontent.com/29458092/61787216-42c93f00-ae07-11e9-971d-f31218f1140e.png)

**Comment by igorbljahhin** [comment]
@BatterBits thanks for pointing me to ports configuration, I found that they are different!

And after thinking I understand now why localhost is OK: Traccar is running in Docker container, which has it web port forwarded to the host and it is 8072, so it should be accessible from Home Assistant too.

So current configuration is 

```
device_tracker:
  - platform: bluetooth_tracker
  - platform: bluetooth_le_tracker
  - platform: traccar
    host: 127.0.0.1
    port: 8072
    ssl: false
    verify_ssl: false
    username: !secret traccar_username
    password: !secret traccar_password
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false
```

and Traccar addon:

![image](https://user-images.githubusercontent.com/1252230/61788534-fab41780-ae1a-11e9-977d-447ffd0a22eb.png)

Traccar addon is working and accepting information from mobile:

![image](https://user-images.githubusercontent.com/1252230/61788563-0acbf700-ae1b-11e9-9e48-eb7ebff64c6b.png)

Home Assistant attempts to connect to Traccar

![image](https://user-images.githubusercontent.com/1252230/61788583-161f2280-ae1b-11e9-83d0-eb0e9e37b88d.png)

But nothing is added to known_devices.yml and to entities:

![image](https://user-images.githubusercontent.com/1252230/61788616-2fc06a00-ae1b-11e9-9473-e1e17cd1682f.png)
